# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9ea7db3f33b775a93bee24d2846a991f174f9ab5d5039f3c305969f9b2ffe4abce64591b481d678f08f556e53fd3e7e7f9e019cce62f39a8da2dc96a336c61f

test:
  secret_key_base: dc0e073ab2a0a43b2dad1682c98df41791d951aa8e7b46c73b93a153ea75ce7867fb3c7c47d2bf775083452bde318071841f65ea67fec7d87d9208b4093066a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
